#菜单导航
menu:
  home: /
  archive: /archives
  category: /categories
  tag: /tags
  about: /about

# 头像
avatar: '/images/head.jpeg'
qq: '/images/qq.jpeg'
wechat: '/images/wechat.jpeg'

# Article default cover image
cover: /images/default-cover.jpg
